#!/bin/bash
# /etc/init.d/AQI
 
### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: aqi sensor-caculator initscript
# Description: This service is used to manage an AQI sensor and caculator 
### END INIT INFO
 
case "$1" in
    start)
        echo "Starting AQI Sensor and caculator"
        python /home/pi/AQI/aqi_main.py &
        ;;
    stop)
        echo "Stopping AQI Sensor and caculator"
        #killall aqi_main.py
        kill $(ps aux | grep -m 1 'python /home/pi/AQI/aqi_main.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service AQI start|stop"
        exit 1
        ;;
esac
exit 0